# Generated by Django 6.0 on 2026-01-04 12:48

import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Unique coupon code (case-insensitive)', max_length=30, unique=True)),
                ('discount_percent', models.PositiveIntegerField(help_text='Percentage discount (e.g., 10 for 10% off)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
                ('valid_from', models.DateTimeField(default=django.utils.timezone.now)),
                ('valid_to', models.DateTimeField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('max_uses', models.PositiveIntegerField(blank=True, help_text='Maximum number of uses (leave blank for unlimited)', null=True)),
                ('used_count', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Coupon',
                'verbose_name_plural': 'Coupons',
                'ordering': ['-valid_from'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, help_text='Contact phone number', max_length=20)),
                ('address', models.TextField(help_text='Full delivery address')),
                ('gps_location', models.CharField(blank=True, help_text='GPS coordinates for precise delivery (e.g., -15.3875, 28.3228)', max_length=100, null=True)),
                ('delivery_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('payment_method', models.CharField(choices=[('airtelmoney', 'Airtel Money'), ('mtn', 'MTN Mobile Money'), ('zamtel', 'Zamtel Kwacha'), ('cash', 'Cash on Delivery')], default='mpesa', max_length=20)),
                ('is_paid', models.BooleanField(default=False)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('processing', 'Processing'), ('shipped', 'Shipped'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('tracking_number', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, help_text='Price at the time of purchase (with discount applied if any)', max_digits=10)),
                ('quantity', models.PositiveIntegerField(default=1)),
            ],
            options={
                'verbose_name': 'Order Item',
                'verbose_name_plural': 'Order Items',
            },
        ),
        migrations.CreateModel(
            name='DeliveryOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g., Standard Delivery, Express Delivery, Instant Pickup', max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=120, unique=True)),
                ('price', models.DecimalField(decimal_places=2, help_text='Delivery fee in Zambian Kwacha (ZMW)', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('estimated_days', models.PositiveSmallIntegerField(help_text='Estimated number of days for delivery', validators=[django.core.validators.MinValueValidator(1)])),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Uncheck to temporarily disable this option without deleting it')),
                ('display_order', models.PositiveSmallIntegerField(db_index=True, default=0, help_text='Lower numbers appear first in the checkout options')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Delivery Option',
                'verbose_name_plural': 'Delivery Options',
                'ordering': ['display_order', 'price', 'name'],
                'indexes': [models.Index(fields=['is_active'], name='orders_deli_is_acti_f45710_idx'), models.Index(fields=['display_order'], name='orders_deli_display_5272b7_idx')],
            },
        ),
    ]
