# Generated by Django 6.0 on 2026-01-06 12:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='promotion',
            name='products_pr_product_6c2bcf_idx',
        ),
        migrations.AlterField(
            model_name='promotion',
            name='product',
            field=models.OneToOneField(default=1, help_text='Product this promotion applies to', on_delete=django.db.models.deletion.CASCADE, related_name='promotion', to='products.product'),
            preserve_default=False,
        ),
    ]
